config:
  credentials: []
  project_repos:
    github.com/DIRACGrid/Pilot:
      branch: master
      repo: https://github.com/DIRACGrid/Pilot
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/DIRACGrid/Pilot git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-aquamarine-kudu.sh
        container: qc.acc_clammy-wisteria-caracal
  QC.Doc:
    repos:
      github.com/DIRACGrid/Pilot find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ultramarine-tzu.sh
        container: qc.doc_hasty-seashell-swan
      github.com/DIRACGrid/Pilot git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-plum-tetra.sh
        container: qc.doc_slaphappy-celadon-slug
      github.com/DIRACGrid/Pilot markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-aqua-whippet.sh
        container: qc.doc_gloppy-plum-grasshopper
      github.com/DIRACGrid/Pilot restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-chestnut-wrasse.sh
        container: qc.doc_snoopy-puce-dolphin
  QC.Lic:
    repos:
      github.com/DIRACGrid/Pilot licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-pear-worm.sh
        container: qc.lic_snazzy-plum-quokka
  QC.Sec:
    repos:
      github.com/DIRACGrid/Pilot bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-sapphire-flamingo.sh
        container: qc.sec_thirsty-teal-hyena
  QC.Sty:
    repos:
      github.com/DIRACGrid/Pilot flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ivory-akita.sh
        container: qc.sty_snoopy-cinnabar-hare
      github.com/DIRACGrid/Pilot jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cobalt-whale.sh
        container: qc.sty_bluesy-lime-javanese
  QC.Uni:
    repos:
      github.com/DIRACGrid/Pilot pytest:
        commands:
        - /usr/bin/env sh .sqa/script.beady-champagne-slug.sh
        container: qc.uni_lumpy-scarlet-dragonfly
  QC.Ver:
    repos:
      github.com/DIRACGrid/Pilot get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-lime-saola.sh
        container: qc.ver_skinny-gamboge-zorse
timeout: 5400
